version: '3'
services:

  # The Robot hmi
  hmi:
    container_name: robot-hmi
    build:
      context: hmi
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./hmi:/usr/src/hmi
      - /usr/src/hmi/node_modules
    restart: always
    networks:
      - hmi-network
    depends_on:
      - api

  # The Robot API
  api:
    container_name: robot-api
    restart: always
    build:
      context: api
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
      - /var/run/dbus:/var/run/dbus
      - /var/lib/bluetooth:/var/lib/bluetooth
      - /etc/bluetooth:/etc/bluetooth
    depends_on:
      - storage
    network_mode: host
    privileged: true
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
      - PYTHON=/usr/bin/python3
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/mem:/dev/mem"

  # MongoDB Storage
  storage:
    container_name: robot-state
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - storage-network
    expose:
      - 27017

networks:
  hmi-network:
  storage-network: