/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./hmi/public/robot_v2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot_v2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.main_column.geometry} material={nodes.main_column.material} position={[0, 1.462, 0]} />
      <mesh geometry={nodes.upper_arm.geometry} material={nodes.upper_arm.material} position={[2.335, 0, 0.094]} scale={[0.684, 1, 1]} />
      <mesh geometry={nodes.wrist_extension.geometry} material={nodes.wrist_extension.material} position={[3.241, 6.541, 0.007]} scale={0.264} />
      <mesh geometry={nodes.hand.geometry} material={nodes.hand.material} position={[3.318, 5.71, -0.101]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.068, 0.327]} />
      <mesh geometry={nodes.gripper.geometry} material={nodes.gripper.material} position={[3.275, 5.505, 0.286]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.01, -0.132, -0.325]} />
    </group>
  )
}

useGLTF.preload('/robot_v2.glb')
